Bugfix/issue5
chrometoasters/silverstripe-metadescription-fallback pull request #6
Opened 2019-12-04 06:47 UTC by normann

This is for #5 with 2 commits,
each commit is targeting fix a sub-issue under #5

2019-12-06 03:23 UTC, michalkleiner requested changes

2019-12-06 03:23 UTC, michalkleiner commented on src/extensions/MetaDescriptionFallbackExtension.php
> +        return singleton($className)->setValue($metaDescription)->ATT();
Please just use `DBText::class` directly. If needed, a custom class can be provided via Injector and is out of scope of this module.

2019-12-08 21:40 UTC, normann commented
Done the requested changes @michalkleiner

2019-12-08 21:44 UTC, michalkleiner approved these changes

2019-12-08 21:45 UTC, michalkleiner commented
Thanks @normann, feel free to merge and tag a new minor release.

2019-12-08 21:58 UTC, merged

2019-12-08 22:08 UTC, normann commented
@michalkleiner just confirm you want me to tag a **minor** release, rather than a **patch** release?

2019-12-10 02:16 UTC, michalkleiner commented
@normann yep, you're right, it can be just a **patch** version.